# Generated by Django 4.2 on 2023-06-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('shop_name', models.CharField(max_length=250)),
                ('password', models.SlugField(max_length=250)),
                ('email', models.SlugField(max_length=250)),
                ('path', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'shopowner',
                'verbose_name_plural': 'shopowners',
            },
        ),
    ]
