# Generated by Django 4.2 on 2023-06-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopowner', '0002_alter_shopowner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopowner',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
