# Generated by Django 4.2 on 2023-06-16 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopowner', '0003_alter_shopowner_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopowner.shopowner')),
            ],
        ),
    ]
