# Generated by Django 4.2 on 2023-06-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopowner', '0004_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopowner',
            name='security_ans',
            field=models.CharField(default=1.9528580076942606e-05, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopowner',
            name='security_qn',
            field=models.CharField(default=0.00012693577050012695, max_length=250),
            preserve_default=False,
        ),
    ]
