# Generated by Django 4.2 on 2023-06-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopowner', '0005_shopowner_security_ans_shopowner_security_qn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopowner',
            name='security_ans',
        ),
        migrations.RemoveField(
            model_name='shopowner',
            name='security_qn',
        ),
        migrations.AddField(
            model_name='shopowner',
            name='referal',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
