# Generated by Django 4.2 on 2023-08-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopowner', '0007_referal'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopowner',
            name='user',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
