# Generated by Django 4.2 on 2023-08-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopowner', '0008_shopowner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopowner',
            name='password',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
