# Generated by Django 4.2 on 2023-06-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaloonFemale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='SaloonFemale')),
                ('path', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'saloonfemale',
                'verbose_name_plural': 'saloonsfemale',
            },
        ),
        migrations.CreateModel(
            name='SaloonMale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='SaloonMale')),
                ('path', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'saloonmale',
                'verbose_name_plural': 'saloonsmale',
            },
        ),
    ]
