# Generated by Django 4.2 on 2023-06-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FemaleServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'femaleservice',
                'verbose_name_plural': 'femaleservices',
            },
        ),
        migrations.CreateModel(
            name='MaleServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'maleservice',
                'verbose_name_plural': 'maleservices',
            },
        ),
    ]
