# Generated by Django 4.2 on 2023-06-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('styleapp', '0002_femaleservices_maleservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='maleservices',
            name='offerprice',
            field=models.DecimalField(decimal_places=2, default=0.0008250825082508251, max_digits=10),
            preserve_default=False,
        ),
    ]
