# Generated by Django 4.2 on 2023-06-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FemaleServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=350)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FemaleShop1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('service', models.CharField(max_length=350)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FemaleShop2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('service', models.CharField(max_length=350)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FemaleShop3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('service', models.CharField(max_length=350)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FemaleShop4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('service', models.CharField(max_length=350)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MaleShop1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('service', models.CharField(max_length=350)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MaleShop2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('service', models.CharField(max_length=350)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MaleShop3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('service', models.CharField(max_length=350)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MaleShop4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('service', models.CharField(max_length=350)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=250)),
            ],
        ),
    ]
