# Generated by Django 4.2 on 2023-06-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FemaleServices',
            new_name='FemaleService',
        ),
    ]
