# Generated by Django 4.2 on 2023-06-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0003_femaleshop1_phone_femaleshop2_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femaleshop1',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='maleshop4',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
