# Generated by Django 4.2 on 2023-06-15 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0004_alter_femaleshop1_phone_alter_maleshop4_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='femaleshop2',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='femaleshop3',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='femaleshop4',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='maleshop1',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='maleshop2',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='maleshop3',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
