# Generated by Django 4.2 on 2023-08-06 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0007_rename_review_reviewfemaleshop1_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewfemaleshop1',
            old_name='reviews',
            new_name='review',
        ),
    ]
