# Generated by Django 4.2 on 2023-07-30 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_delivary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivary',
            name='active',
        ),
        migrations.RemoveField(
            model_name='delivary',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='delivary',
            name='cart_items',
        ),
        migrations.RemoveField(
            model_name='delivary',
            name='product',
        ),
        migrations.RemoveField(
            model_name='delivary',
            name='quantity',
        ),
    ]
